/* Generated by Yosys 0.34+7 (git sha1 fc815fdb4, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module fa(a, b, cin, sum, co);
  input a;
  wire a;
  input b;
  wire b;
  input cin;
  wire cin;
  output co;
  wire co;
  wire co1;
  wire co2;
  wire \ins1.a ;
  wire \ins1.b ;
  wire \ins1.co ;
  wire \ins1.sum ;
  wire \ins2.a ;
  wire \ins2.b ;
  wire \ins2.co ;
  wire \ins2.sum ;
  output sum;
  wire sum;
  wire sum1;
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0_ (
    .A(co2),
    .SLEEP(co1),
    .X(co)
  );
  sky130_fd_sc_hd__and2_0 _1_ (
    .A(\ins1.b ),
    .B(\ins1.a ),
    .X(\ins1.co )
  );
  sky130_fd_sc_hd__xor2_1 _2_ (
    .A(\ins1.b ),
    .B(\ins1.a ),
    .X(\ins1.sum )
  );
  sky130_fd_sc_hd__and2_0 _3_ (
    .A(\ins2.b ),
    .B(\ins2.a ),
    .X(\ins2.co )
  );
  sky130_fd_sc_hd__xor2_1 _4_ (
    .A(\ins2.b ),
    .B(\ins2.a ),
    .X(\ins2.sum )
  );
  assign \ins2.a  = cin;
  assign \ins2.b  = sum1;
  assign co2 = \ins2.co ;
  assign sum = \ins2.sum ;
  assign \ins1.a  = a;
  assign \ins1.b  = b;
  assign co1 = \ins1.co ;
  assign sum1 = \ins1.sum ;
endmodule
