/* Generated by Yosys 0.34+7 (git sha1 fc815fdb4, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module fa(a, b, cin, sum, co);
  input a;
  wire a;
  input b;
  wire b;
  input cin;
  wire cin;
  output co;
  wire co;
  wire co1;
  wire co2;
  output sum;
  wire sum;
  wire sum1;
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0_ (
    .A(co2),
    .SLEEP(co1),
    .X(co)
  );
  ha ins1 (
    .a(a),
    .b(b),
    .co(co1),
    .sum(sum1)
  );
  ha ins2 (
    .a(cin),
    .b(sum1),
    .co(co2),
    .sum(sum)
  );
endmodule

module ha(a, b, sum, co);
  input a;
  wire a;
  input b;
  wire b;
  output co;
  wire co;
  output sum;
  wire sum;
  sky130_fd_sc_hd__and2_0 _0_ (
    .A(b),
    .B(a),
    .X(co)
  );
  sky130_fd_sc_hd__xor2_1 _1_ (
    .A(b),
    .B(a),
    .X(sum)
  );
endmodule
